// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package file_repository

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Size                 int32                `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	UserId               int32                `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	File                 []byte               `protobuf:"bytes,5,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *File) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *File) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *File) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type SaveFileRequest struct {
	File                 []byte   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveFileRequest) Reset()         { *m = SaveFileRequest{} }
func (m *SaveFileRequest) String() string { return proto.CompactTextString(m) }
func (*SaveFileRequest) ProtoMessage()    {}
func (*SaveFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1}
}

func (m *SaveFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveFileRequest.Unmarshal(m, b)
}
func (m *SaveFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveFileRequest.Marshal(b, m, deterministic)
}
func (m *SaveFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveFileRequest.Merge(m, src)
}
func (m *SaveFileRequest) XXX_Size() int {
	return xxx_messageInfo_SaveFileRequest.Size(m)
}
func (m *SaveFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveFileRequest proto.InternalMessageInfo

func (m *SaveFileRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *SaveFileRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetFileRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileRequest) Reset()         { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()    {}
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{2}
}

func (m *GetFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileRequest.Unmarshal(m, b)
}
func (m *GetFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileRequest.Marshal(b, m, deterministic)
}
func (m *GetFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileRequest.Merge(m, src)
}
func (m *GetFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileRequest.Size(m)
}
func (m *GetFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileRequest proto.InternalMessageInfo

func (m *GetFileRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*File)(nil), "file.repository.File")
	proto.RegisterType((*SaveFileRequest)(nil), "file.repository.SaveFileRequest")
	proto.RegisterType((*GetFileRequest)(nil), "file.repository.GetFileRequest")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xcb, 0xcc, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x07, 0xb3, 0x8b, 0x52, 0x0b, 0xf2, 0x8b, 0x33,
	0x4b, 0xf2, 0x8b, 0x2a, 0xa5, 0xe4, 0xd3, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0xd2, 0x49,
	0xa5, 0x69, 0xfa, 0x25, 0x99, 0xb9, 0xa9, 0xc5, 0x25, 0x89, 0xb9, 0x05, 0x10, 0x1d, 0x4a, 0x93,
	0x18, 0xb9, 0x58, 0xdc, 0x80, 0x9a, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x58, 0x83, 0x80, 0x2c, 0x21, 0x4b, 0x2e, 0xae, 0xe4, 0xa2, 0xd4, 0xc4, 0x92, 0xd4, 0x94,
	0xf8, 0xc4, 0x12, 0x09, 0x26, 0xa0, 0x38, 0xb7, 0x91, 0x94, 0x1e, 0xc4, 0x38, 0x3d, 0x98, 0x71,
	0x7a, 0x21, 0x30, 0xe3, 0x82, 0x38, 0xa1, 0xaa, 0x1d, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0x8a, 0x33,
	0xab, 0x52, 0x25, 0x98, 0xc1, 0x86, 0x81, 0xd9, 0x42, 0xe2, 0x5c, 0xec, 0xa5, 0xc5, 0xa9, 0x45,
	0xf1, 0x40, 0x3b, 0x58, 0xc0, 0xc2, 0x6c, 0x20, 0xae, 0x67, 0x0a, 0x48, 0x31, 0xc8, 0xd1, 0x12,
	0xac, 0x40, 0x51, 0x9e, 0x20, 0x30, 0x5b, 0xc9, 0x8e, 0x8b, 0x3f, 0x38, 0xb1, 0x2c, 0x15, 0xe4,
	0xae, 0xa0, 0xd4, 0xc2, 0x52, 0xa0, 0x0d, 0x70, 0x65, 0x8c, 0x08, 0x65, 0xc8, 0x66, 0x32, 0x21,
	0x9b, 0xa9, 0xa4, 0xc0, 0xc5, 0xe7, 0x9e, 0x5a, 0x82, 0xac, 0x1d, 0xcd, 0x77, 0x49, 0x6c, 0x60,
	0x1f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x68, 0x91, 0x71, 0x21, 0x3d, 0x01, 0x00, 0x00,
}
